In [18]:
import random as random
import numpy as np

In [19]:
#define class graph
class graph:
    def __init__(self,n,adj):
        self.n=n
        self.adj=adj

In [20]:
#define fitness scoring by calculating number of bad edges
def fitness(gr,sample):
        score=0
        for i in range(gr.n):
            for j in range(gr.n):
                if ( (gr.adj[i,j]==1) and (sample[i]==sample[j]) and (i!=j) ):
                    score=score+1      
        return int(score/2)

In [21]:
def parentselection1(population,gr):
    
    #choose first parent
    x=random.choice(population)
    y=random.choice(population)
    if(fitness(gr,x) <= fitness(gr,y) ):
        parent1=x
    else:
        parent1=y
    #choose second parent    
    x=random.choice(population)
    y=random.choice(population)
    if(fitness(gr,x) <= fitness(gr,y) ):
        parent2=x
    else:
        parent2=y
        
    return parent1,parent2


In [22]:
def Bestfitness(population,gr):
    population_size=len(population)
    #evaluate fitness of all population
    allfitnessscore=[]
    for i in range(population_size):
        allfitnessscore.append( fitness(gr,population[i]) )    
    bestfitness=min(allfitnessscore) 
    return bestfitness,allfitnessscore.index( bestfitness )

In [23]:
def sortbyfitness(population,gr): 
    for i in range(len(population)):
        k=i
        for j in range(i+1,len(population)):
            if ( fitness(gr,population[k])> fitness(gr,population[j]) ):
                population[k],population[j]=population[j],population[k]
    return(population)

In [24]:
def parentselection2(population,gr):   
    #choose  the top performing chromosome    
    bestfitness,Index1=Bestfitness(population,gr)
    return population[Index1],population[Index1] 


In [25]:
def Crossover(parent1,parent2):
    CrossPoint = random.randint(0,len(parent1)-1)
    Child = parent1[:CrossPoint+1] + parent2[CrossPoint+1:]
    return Child


In [26]:
def mutation1(gr,numberof_colors,sample):
        all_colors=range(1,numberof_colors+1)
        for i in range(gr.n):
            adjacent_colors=[]
            valid_colors=[]
            for j in range(gr.n):
                if (gr.adj[i,j]==1) and (sample[i]==sample[j]):
                    for k in range(gr.n):
                        if (gr.adj[i,k]==1):
                            adjacent_colors.append(sample[k])             
            adjacent_colors=list(set(adjacent_colors))
            valid_colors=list(set(all_colors)-set(adjacent_colors))
            if(len(valid_colors)==0):
                print("PROBLEM : Number of colors is not enough to color all graph")
            new_color=random.choice(valid_colors)
            sample[i]=new_color
        return sample     

In [27]:
def mutation2(gr,numberof_colors,sample):
        all_colors=range(1,numberof_colors+1)
        for i in range(gr.n):
            for j in range(gr.n):
                if (gr.adj[i,j]==1)and (sample[i]==sample[j]):
                    new_color=random.choice(all_colors)
                    sample[i]=new_color
        return sample            

In [29]:
def general_genetic_algorithm(numberof_colors,max_generation_number,gr):
    population_size=50
    mid_point=25
    
    #population = randomly generated chromosomes
    population=[]
    for i in range(population_size):
        cr=[]
        for i in range(gr.n):    
            #ramdomly choose table of colors
            cr.append(random.randint(1,numberof_colors))
        #add to population
        population.append(cr)
        
    #run general genetic algorithm    
    generation_number=0
    best_fitness=351286532  
    k=0
    while( (generation_number<max_generation_number) or (best_fitness!=0) ):
        
        #evaluate fitness of all population
        best_fitness,Index1=Bestfitness(population,gr)
        t=best_fitness
        if(generation_number==0):
            print("best fitness to begin with: ",t)
        #create children    
        children=[]
        if (best_fitness>=4):
            for i in range (len(population)+1):
                parent1,parent2=parentselection1(population,gr)
                child=Crossover(parent1,parent2)
                child=mutation1(gr,numberof_colors,child)
                children.append(child)
        else:
            for i in range (len(population)+1):
                parent1,parent2=parentselection2(population,gr)
                child=Crossover(parent1,parent2)
                child=mutation2(gr,numberof_colors,child)
                children.append(child)
        
        #update population
        population=sortbyfitness(population,gr)
        for i in range(mid_point,population_size):
            population[i]=children[i-mid_point]
        #evaluate fitness of all population
        best_fitness,Index1=Bestfitness(population,gr)    

        #add number of generations
        generation_number=generation_number+1
        if(t!=best_fitness):
            print("best fitness found in " ,generation_number,"generation step :",best_fitness) 
        else:
            k=k+1
        if(k==53):
            break
    print("the algorithm found a solution after :",generation_number,"generation steps with fitness :",best_fitness)   
    return population        

In [30]:
def random_matrix(n):
    m=np.ones( (n,n) )
    for i in range(n-1):
        for j in range(i+1,n):
            m[i][j]=random.randint(0,1)
            m[j][i]=m[i][j]
    return m

In [35]:
#input example:
n=10
adj=random_matrix(n)
print("nmuber of vertex: ",n)
print("adjency matrix:\n",adj)
gr=graph(n,adj)

nmuber of vertex:  10
adjency matrix:
 [[1. 1. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1. 1. 1. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 1. 0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 1. 0. 1. 1. 1.]
 [1. 0. 1. 0. 0. 1. 1. 1. 1. 1.]]


In [45]:
#choose parameters
numberof_colors= 4
max_generation_number=1000

#run genetic algorithm with chosen parameters
final_population=general_genetic_algorithm(numberof_colors,max_generation_number,gr)

best fitness to begin with:  2
best fitness found in  1 generation step : 1
the algorithm found a solution after : 54 generation steps with fitness : 1


In [42]:
#results:
#find the bestchromoson that has fitness=0 with minimum number of colors
index_minimum_colors=0
test=0 
for i in range( len(final_population) ):
    if(fitness(gr,final_population[i])==0):
        test=1
        actual_value=len(set(final_population[index_minimum_colors]))
        i_value=len( set(final_population[i]) )
        if( actual_value > i_value ):
            index_minimum_colors=i
#test if the algorithm failed to find correct solution            
if(test==0) :
    print("Number of generations is not enough to find a correct solution ")
else :   
    print("a good solution for the problem using the number of colors ",actual_value,"is:\n")
    print("befor correction:\n" ,final_population[ index_minimum_colors] )
    
    #colors rank optimazation
    colors=set( final_population[ index_minimum_colors] )
    final_solution=final_population[ index_minimum_colors]
    k=1
    for x in colors:
        for i in range(len(final_solution)):
            if(final_solution[i]==x):
                final_solution[i]=k
        k=k+1
    print("after correction:\n",final_solution)  
    print("fitness error: ",fitness(gr,final_solution))

a good solution for the problem using the number of colors  4 is:

befor correction:
 [1, 2, 3, 2, 2, 1, 4, 3, 4, 2]
after correction:
 [1, 2, 3, 2, 2, 1, 4, 3, 4, 2]
fitness error:  0
